app/models.py
from datetime import datetime
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

class Game(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(40))
    body = db.Column(db.Text)
    def __repr__(self):
        return '<Game {}>'.format(self.title)

app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User,Game


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

class GameForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = StringField('Body', validators=[DataRequired()])
    submit = SubmitField('Submit')

class BianjiGameForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = StringField('Body', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)


app.config['SQLALCHEMY_DATABASE_URI'] ='mysql+pymysql://root:zxc510626@127.0.0.1:3306/app?charset=utf8'
app.config['SECRET_KEY'] = "tse"
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = 'admin.login'
from app.admin import bp as admin_bp
app.register_blueprint(admin_bp,url_prefix='/admin')
from app.user import bp as user_bp
app.register_blueprint(user_bp,url_prefix='/user')

app/admin/__init__.py
from flask import Blueprint
bp = Blueprint('admin',__name__)
from app.admin import routes

app/admin/routes.py
from app import app,db
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse
from app.admin import bp
from app.admin.forms import LoginForm, RegistrationForm,GameForm,BianjiGameForm
from app.models import User,Game
@bp.route('/')
@bp.route('/index')
@login_required
def index():
    games = Game.query.all()
    return render_template('index.html', title='Home', games=games)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('admin.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('admin.index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)


@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('admin.index'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('admin.login'))
    return render_template('register.html', title='Register', form=form)

@bp.route('/editgame',methods=['GET','POST'])
@login_required
def editgame():
    form = GameForm()
    if form.validate_on_submit():
        game = Game(title=form.title.data, body=form.body.data) 
        db.session.add(game)
        db.session.commit()
        return redirect(url_for('admin.index'))
    return render_template('editgame.html',title='Editgame',form=form)

@bp.route('/bianjigame',methods=['GET','POST'])
@login_required
def bianjigame():
    gamename = request.args.get("title")
    gamebody = request.args.get("body")
    form = BianjiGameForm(gamename)
    if form.validate_on_submit():
        game = Game(title=form.title.data,body=form.body.data)
        db.session.commit()
        flash('ok')
        return redirect(url_for('admin.index'))
    elif request.method == 'GET':
        gamename = request.args.get("title")
        gamebody = request.args.get("body")
    
    return render_template('bianjigame.html',title='Bianji',form=form) 

app/user/__init__.py
from flask import Blueprint 
bp = Blueprint('user',__name__)
from app.user import routes

app/user/routes.py
from flask import Flask
from app.user import bp

@bp.route('/index2')
def index2():
	return "user"

app/templates/base.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - Microblog</title>
        {% else %}
        <title>Welcome to Microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            Microblog:
            <a href="{{ url_for('admin.index') }}">Home</a>
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('admin.login') }}">Login</a>
            {% else %}
            <a href="{{ url_for('admin.logout') }}">Logout</a>
            {% endif %}
	    <a href="{{ url_for('admin.editgame') }}">Editgame</a>
        </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/bianjigame.html
{% extends "base.html" %}
{% block content %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}<br>
        </p>
        <p>
            {{ form.body.label }}<br>
            {{ form.body(size=80) }}<br>
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/editgame.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <label>Title</label>
    <input type="text" name="title">
    <label>Body</label>
    <input type="text" name="body">
    <p>{{ form.submit() }}</p>

</form>
{% endblock %}

app/templates/gamelist.html
{% extends "base.html" %}

{% block content %}
{% if games %}
    {% for game in games%}
        <h3><a href="{{ url_for('admin.editgame',title=game.title> }}">{{game.title}}</a></h3>
    {% endfor %}
{% else %}
    <p></p>
    <a ></a>
{% endif %}


{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% for game in games %}
    <p><a href="{{ url_for('admin.bianjigame',title=game.title) }}">{{ game.title }}</a><b>{{ game.body }}</b></p>
    {% endfor %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('admin.register') }}">Click to Register!</a></p>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}